baseurl = "/"
languageCode = "en-us"
title = "LTER-CZO-NEON soil organic matter synthesis"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# How do I add a title to the header?
#LTER-CZO-NEON soil organic matter synthesis


# how do we format these, with title, no date in a particular order?
[permalinks]
    post = "/:year/:month/:day/:slug/"

# how do I point to the home page?
[[menu.main]]
    name = "Home"
    url = "/about/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lter/lterwg-som"

[[menu.main]]
    name = "LTER"
    url = "https://lternet.edu/"

[params]
    description = "A website for the LTER soil organic matter synthesis working group"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

